- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
        debug:
          msg: "Hello World!"
    - name: Hello Message
      copy:
        contents: “Hello Ansible world!”
        dest: /root/hello
        perms: 0444
        owner: root

